name: AdventOfCode2019
version: 0.1
github: "darichey/AdventOfCode2019"
license: MIT

dependencies:
- base >= 4.7 && < 5
- split
- vector
- containers
- fgl
- linear
- parsec
- lens

executable:
  main: Main.hs
  source-dirs: src