name: AdventOfCode
version: 0.1
github: "darichey/AdventOfCode"
license: MIT

dependencies:
- base >= 4.7 && < 5
- split
- vector
- containers
- linear
- lens
- text # only used for Year2019.Day13
- cmdargs
- either
- megaparsec
- cryptohash-md5 # only used for Year2015.Day04
- bytestring # only used for Year2015.Day04
- base16-bytestring # only used for Year2015.Day04
- parser-combinators

executables:
  AdventOfCode-exe:
    main: Main.hs
    source-dirs: AdventOfCode

ghc-options:
- -Wall