name: AdventOfCode
version: 0.1
github: "darichey/AdventOfCode"
license: MIT

dependencies:
- base >= 4.7 && < 5
- split
- vector
- containers
- fgl
- linear
- parsec
- parsec-numbers
- lens
- text
- cmdargs
- ordered-containers
- either

executables:
  AdventOfCode-exe:
    main: Main.hs
    source-dirs: AdventOfCode